env: env
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///po110
    driver-class-name: com.mysql.jdbc.Driver
#    消息中间架
  rabbitmq:
    host: 192.168.0.106
    username: guest
    password: guest
    port: 5672
server:
  port: 8089
#修改名为PRODUCT服务器的策略
PRODUCT:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

