env: productdev8
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8762/eureka
server:
  port: 8088
spring:
  application:
    name: product
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///po110
    driver-class-name: com.mysql.jdbc.Driver
    #    消息中间架
  rabbitmq:
    host: 192.168.0.106
    username: guest
    password: guest
    port: 5672
